import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[cursor.style]
blinking = "Never"

[font]
size = 16

[font.normal]
family = "SF Mono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10
