import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[font]
size = 16

[font.normal]
family = "SF Mono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 0

[shell]
args = ["new", "-A", "-s", "MASTER"]
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10
