import = [
# "~/.config/alacritty/colorschemes/ayu-dark.toml",
# "~/.config/alacritty/colorschemes/catppuccin-frappe.toml",
# "~/.config/alacritty/colorschemes/catppuccin-macchiato.toml",
# "~/.config/alacritty/colorschemes/catppuccin-mocha.toml",
# "~/.config/alacritty/colorschemes/custom-light.toml",
# "~/.config/alacritty/colorschemes/doom-one.toml",
# "~/.config/alacritty/colorschemes/dracula.toml",
# "~/.config/alacritty/colorschemes/github-dark.toml",
# "~/.config/alacritty/colorschemes/gruvbox-dark.toml",
# "~/.config/alacritty/colorschemes/gruvbox-powerline.toml",
# "~/.config/alacritty/colorschemes/gruvbox.toml",
# "~/.config/alacritty/colorschemes/modus-operandi.toml",
# "~/.config/alacritty/colorschemes/modus-vivendi.toml",
# "~/.config/alacritty/colorschemes/monokai.toml",
# "~/.config/alacritty/colorschemes/moonfly.toml",
# "~/.config/alacritty/colorschemes/nord.toml",
# "~/.config/alacritty/colorschemes/oceanic-next.toml",
# "~/.config/alacritty/colorschemes/onedark.toml",
# "~/.config/alacritty/colorschemes/papercolor.toml",
# "~/.config/alacritty/colorschemes/solarized-dark.toml",
# "~/.config/alacritty/colorschemes/solarized-light.toml",
# "~/.config/alacritty/colorschemes/sonokai.toml",
# "~/.config/alacritty/colorschemes/tokyonight-storm.toml",
# "~/.config/alacritty/colorschemes/tokyonight.toml",
# "~/.config/alacritty/colorschemes/tomorrow-night.toml"
]
