set visualbell
set noerrorbells

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set encoding=utf-8
set fileencoding=utf-8

set smartindent
set autoindent

set colorcolumn=80

set nocompatible
" set backspace=2
" set wildmode=full
set pumheight=5         " this limits the popup to show 5 items
set complete+=k         " this tells vim to look up the dictionary words
set completeopt=menuone,noselect
set shortmess+=c        " this tells not to show msg in bottom while selecting items from popup menu
set spell
set spelllang=en_us
set dictionary+=/usr/share/dict/words

set textwidth=80        " shorthand tw
set formatoptions+=t    " shorthand fo
set formatoptions+=n
set formatoptions+=2
" set formatoptions+=a

set splitbelow
set splitright

set noswapfile
set showcmd

filetype plugin indent on

inoremap jj         <ESC>

let loaded_matchparen = 1

set list
set listchars=trail:-,tab:>-
autocmd BufWritePre * :%s/\s\+$//e

set foldmethod=marker

set viminfofile=~/.vim/viminfo
