call plug#begin()

Plug 'junegunn/limelight.vim'
Plug 'junegunn/goyo.vim'
Plug 'SyedFasiuddin/nop.vim'

call plug#end()

set visualbell
set noerrorbells

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

set encoding=utf-8
set fileencoding=utf-8

set smartindent
set autoindent

set colorcolumn=80

set nocompatible
" set backspace=2
" set wildmode=full
set pumheight=5         " this limits the popup to show 5 items
set complete+=k         " this tells vim to look up the dictionary words
set completeopt=menuone,noselect
set shortmess+=c        " this tells not to show msg in bottom while selecting items from popup menu
set spell
set spelllang=en_us
set dictionary+=/usr/share/dict/words

set textwidth=80        " shorthand tw
set formatoptions+=t    " shorthand fo
set formatoptions+=n
set formatoptions+=2
" set formatoptions+=a

set splitbelow
set splitright

set noswapfile
set showcmd

let g:limelight_conceal_ctermfg = 240
let g:limelight_conceal_guifg = '#777777'
let g:limelight_default_coefficient = 0.7

let g:goyo_width=80
let g:goyo_height="60%"

function! s:goyo_enter()
    if executable('tmux') && strlen($TMUX)
        silent !tmux set status off
    endif

    set noshowcmd
    set scrolloff=999
    Limelight
endfunction

function! s:goyo_leave()
    if executable('tmux') && strlen($TMUX)
        silent !tmux set status on
    endif

    set showcmd
    set scrolloff=0
    Limelight!
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()

filetype plugin indent on

inoremap jj         <ESC>
nnoremap <F2>       :Goyo<CR>
inoremap <F2>       <ESC>:Goyo<CR>a

let loaded_matchparen = 1

set list
set listchars=trail:-,tab:>-
autocmd BufWritePre * :%s/\s\+$//e

set foldmethod=marker
