#!/usr/bin/env sh

# Do not manage anything on first space and let MacOS do its things, on every
# other space manage the windows.
yabai -m config --space 1 layout float
yabai -m config           layout bsp

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config top_padding     10
yabai -m config bottom_padding  10
yabai -m config left_padding    10
yabai -m config right_padding   10
yabai -m config window_gap      10

# Few apps on MacOS have specific requirements of minimum height and width and
# when tiled they will not respect the new width and height and overlap with
# other windows. So just bail out from trying to manage such apps.
yabai -m rule --add app="^Activity Monitor$"    manage=off
yabai -m rule --add app="^App Store$"           manage=off
yabai -m rule --add app="^Archive Utility$"     manage=off
yabai -m rule --add app="^Calculator$"          manage=off
yabai -m rule --add app="^Calendar$"            manage=off
yabai -m rule --add app="^Messages$"            manage=off
yabai -m rule --add app="^Music$"               manage=off
yabai -m rule --add app="^System Settings$"     manage=off
yabai -m rule --add app="^Telegram$"            manage=off
yabai -m rule --add app="^WhatsApp$"            manage=off
