#! /bin/bash

function update () {
    # if a session named update exixts then attach to it else create it.
    if tmux attach -t update ; then
        # send command to update
        tmux send-keys -t "update":1 "sudo dnf update && sudo dnf upgrade -y" C-m
    else
        tmux new -d -s update
        # send command to update
        tmux send-keys -t "update":1 "sudo dnf update && sudo dnf upgrade -y" C-m
        # attach to session so that I can enter sudo passwd
        tmux a -t update
    fi
}
